<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % ADC.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

In the early 1990s, we designed and created <a href="legacy">LightWatch</a>, a 
sophisticated, highly graphical, SNMP-based network management 
system for managing and controlling multi-protocol LAN's.
<br><br>
The underlying graphics interface for the MS-DOS version
used the <a href="legacy">B&auml;cchus Window Management System</a>, a proprietary,
platform independent window management system and widget 
library. These tools were licensed to Fibermux by B&auml;cchus.
<br><br>
B&auml;cchus was also responsible for the look & feel and 
graphic asset generation for both the UNIX and MS-DOS versions
of LightWatch.