<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % CarsDirect.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Wrote, integrated, setup, deployed, and maintained real-time 
web-based customer service tool&#x2014;eLiveAdvisor. This tool is 
currently in service providing live on-line support on the 
<A HREF="http://www.carsdirect.com/" target="new">CarsDirect.com</A> 
web site.
<br><br>
We also helped develop and deploy proprietary J2EE technology used 
in the real-time web-based customer service system and other 
back-end systems used to ensure <A HREF="http://www.contactpath.com/products.htm" target="new">web site up-time 
</A>.
<br><br>
Other work included design and implementation of an EAI solution, 
which processed their two-month and growing backlog of orders 
in a single night and the solution to numeruous Java, Javascript, 
HTML, and web site integration problems.


