<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % fivesuare.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Joined a team of 20+ J2EE developers as the primary 
user interface developer for <a target="_new" href="http://www.5square.com/">DealSnap</a> 4.x&#x2014;5square's Customer   
Resource Management (CRM) Web application for Car Dealerships.
<br><br>
Front end development with JSP's, servlets, custom taglibs, DHTML, DOM, JavaScript
and CSS.
<br><br>
Developed on a Windows XP/Pro platform using JBOSS 4.x/Tomcat. Deployed
on a Linux platform with Apache/JBOSS.
