<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Ixia.jsp 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Our work for Ixia included the design and implementation of 
IxCore, a 
fundamental part of Ixia's NetOps
suite of products for optimizing and monitoring network traffic.
<br><br>
System included Java-based central server for collecting,
aggregating, and storing data from Ixia's hardware nodes. JSPs 
and servlets provided browser-based monitoring front-end, including 
various on-demand and prerendered report graphs, logging, and a 
management UI.
<br><br>
IxCore is platform, application server, and database independent and 
runs on Linux and Windows&nbsp;NT/2000.
	