<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Path.jsp 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

As members of the core development team at Path Communications, we worked on 
<A HREF="http://www.contactpath.com/products.htm" target="new">P.A.M.</A>, 
an application manager and automatic recovery system, and eLiveAdvisor, 
a realtime web communication technology.
<br><br>
Our work included design, development and deployment of core Java 
client/server multi-threaded distributed applications using RMI and Java&nbsp;2, 
heterogeneous system and network administration, Apache, IIS, SSL, servlets, JRun, Oracle,
Perl, JSP, and JavaScript. 
<br><br>
This technology is currently being used on several high-profile web sites, including 
<A HREF="http://www.carsdirect.com/" target="new">CarsDirect.com</A>, 
<A HREF="http://www.lrn.com/" target="new">LRN</A>, and 
<A HREF="http://www.pratt-whitney.com/" target="new">Pratt &amp;&nbsp;Whitney</A>.
