<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % PrattAndWitney.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Lead developer on Pratt &amp;&nbsp;Whitney's real-time aircraft parts 
procurement reverse auction web site&#x2013;&nbsp;<A HREF="http://www.aerooffer.com" target="NEW">AeroOffer.com</A>. 
<br><br>
This project involved extensive Java client/server, servlet,
and JavaScript development.
