<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Rendition.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

In the mid-1990s, B&auml;cchus designed and implemented a
high-resolution, cross-platform, realtime 6-DOF <A HREF="mirage/technology.html">3D graphics 
engine</A>, including an accelerated implementation for the 
<A HREF="http://www.rendition.com/" target="new"> Rendition 
V&eacute;rit&eacute;</A>. 
<br><br>
We used the V&eacute;rit&eacute; implementation to create a 
technology demo for Rendition, showing off the features of their 
V2000 3D chips. Demo highlights included real-time video 
feed and <A HREF="mirage/gallery.html">true reflections</A>.
<br><br>
We also helped debug problems in their graphic chip firmware and 
video driver software.
