<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Smithsonian.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Designed, wrote, and installed an interactive computer, 
touch-screen-based digital music exhibit at the Smithsonian 
museum in Washington DC.
<br><br>
This exhibit allowed users to select and play musical pieces of 
various styles and periods. The selected MIDI music files were 
played through a 
<a href="http://www.yamahamusicsoft.com/disklavier/hardware.php" target="new">Disklavier</a>&#x2014;Yamaha's 
digital/acoustic piano with MIDI electronic connections.

