<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Sun.jsp 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->


Our primary task was to port the Netscape
<A HREF="http://developer.netscape.com/docs/manuals/ifc/home.html" target="new">IFC's</A>
look and feel using <A HREF="http://java.sun.com/products/jfc/tsc/" target="new">Swing</A> 
(then still secret) and the AWT, producing what is now 
called the Elegance Look&nbsp;and Feel. 
<br><br>
Approximately fifty classes were involved covering the full 
spectrum of graphical user interface widgets: windows, buttons, 
scrollbars, sliders, etc.
<br><br>
We are particularly experienced implementing pluggable 
look-and-feels using Swing. We also helped Sun remove a number of bugs.