<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Viacom.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

Designed <A HREF="mirage/index.html">Mirage</A>, an innovative 3D interactive 
adventure game for Viacom New Media (a Viacom International subsidiary) to
help inspire interest in mathematics in teenagers. 
<br><br>
We were responsible for the original story material, game design and the 
management of several writing teams, graphic houses, and game designers.
<br><br>
B&auml;cchus also created the underlying <A HREF="mirage/technology.html">3D 
graphics engine</A> and associated technology.
