<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Web i18n.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

As a member of the core <a href="http://www.web-i18n.net/" target="new">Web&nbsp;i18n</a>
development group, B&auml;cchus helped design, manage and implement multi-lingual J2EE-based
real estate web applications&#x2013;<a href="http://www.web-i18n.net/web-i18n/products" target="new">i18ngenious</a> and associated content
management system&#x2013;<a href="http://www.web-i18n.net/web-i18n/products" target="new">agent.i18ngenious</a>.
<br><br>
Initial offering supports Traditional Chinese, Simplified 
Chinese, and English. 
<br><br>
Japanese and Spanish locales will be 
added soon.

