<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % WorldSite.jsp 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->
 
Helped develop ComBill, 
Worldsite's Java-based e-commerce software system, including check
and credit card payment processing.
<br><br>
Other work included implementation of SSL and other security 
for electronic payments and the development of a flashy, 
Java Swing-based, 
multi-threaded console application to monitor server farm liveliness 
and alert system administrators upon warning and failure conditions. 
<br><br>
These applications are currently in production at 
<A HREF="http://www.webcountry.net/" target="new">Webcountry</A> 
(formerly WorldSite Networks) on Linux, UNIX and Windows.

