<!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %
 % Yamaha.inc 
 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->
Worked for the 
<A HREF="http://www.yamaha.co.jp/english/product/lsi/us/index.html" target="new">Yamaha Systems Technology</A> Group 
writing low-level assembly language video device drivers
to support various high-resolution graphics chips and demos 
for third party flat panel displays.
<br><br>
Our relationship with the Yamaha Music Group (YMG) led to 
B&auml;cchus delivering the first
commercial <a href='legacy'>IBM-PC graphic editing systems</a> for Yamaha's popular digitial FM 
synthesizers and rack-mount tone generators&#x2014;the TX81Z and TX802.
<br><br>
Work for the YMG also included being
one of the first developers to work with and support the 
Yamaha C1 Music Computer, the first laptop computer with 
built-in MIDI hardware.



